<a href="https://colab.research.google.com/github/Saisneha0209/Machine-Learning/blob/main/SPAM_HAM__PROJECT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import pandas as pd
df = pd.read_csv(
    "spam.csv",
    encoding="latin-1"
)
df = df[["v1", "v2"]]
df.columns = ["label", "text"]
df["label"] = df["label"].map({
    "ham": 0,
    "spam": 1
})
X = df["text"].fillna("").astype(str)
y = df["label"]

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X_vectorized = vectorizer.fit_transform(X)

print(X_vectorized)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 73916 stored elements and shape (5572, 8672)>
  Coords	Values
  (0, 3550)	0.1481298737377147
  (0, 8030)	0.22998520738984352
  (0, 4350)	0.3264252905795869
  (0, 5920)	0.2553151503985779
  (0, 2327)	0.25279391746019725
  (0, 1303)	0.24415547176756056
  (0, 5537)	0.15618023117358304
  (0, 4087)	0.10720385321563428
  (0, 1751)	0.2757654045621182
  (0, 3634)	0.1803175103691124
  (0, 8489)	0.22080132794235655
  (0, 4476)	0.2757654045621182
  (0, 1749)	0.3116082237740733
  (0, 2048)	0.2757654045621182
  (0, 7645)	0.15566431601878158
  (0, 3594)	0.15318864840197105
  (0, 1069)	0.3264252905795869
  (0, 8267)	0.18238655630689804
  (1, 5504)	0.27211951321382544
  (1, 4512)	0.4082988561907181
  (1, 4318)	0.5236458071582338
  (1, 8392)	0.4316010362639011
  (1, 5533)	0.5465881710238072
  (2, 4087)	0.07917128722158312
  (2, 3358)	0.11301399735581102
  :	:
  (5570, 4218)	0.12246610191126918
  (5570, 8313)	0.18723687600522523
  (5570, 1084)	0.11225268140936363
  (5570, 4615)	0.1596552981734164
  (5570, 7039)	0.18426763178390446
  (5570, 3308)	0.12172172618634511
  (5570, 7627)	0.10242646659763287
  (5570, 1438)	0.1429585509124154
  (5570, 5334)	0.21003730857873562
  (5570, 2592)	0.18458634504313887
  (5570, 8065)	0.2088086209859756
  (5570, 1778)	0.13664567516026058
  (5570, 7049)	0.205343868729306
  (5570, 2892)	0.2440099568063893
  (5570, 3470)	0.2752778321471702
  (5570, 1786)	0.28292057870729176
  (5570, 3687)	0.242516196245848
  (5570, 4161)	0.28292057870729176
  (5570, 903)	0.32476233976158125
  (5570, 1546)	0.340204888824892
  (5571, 7756)	0.14849350328973984
  (5571, 5244)	0.39009002726386227
  (5571, 4225)	0.5773238083586979
  (5571, 7885)	0.42752913176432156
  (5571, 6505)	0.5565029307246045

In [35]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state =42
)

print(x_train.shape)
print(x_test.shape)

(4457,)
(1115,)

In [36]:
x_vectorised = vectorizer.fit_transform(x_train)
x_test_vectorised = vectorizer.transform(x_test)

In [37]:
'''from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score , classification_report
model = MultinomialNB()
#model.fit(x_train,y_train)
y_pred = model.predict(x_test)
accuracy = accuracy_score(y_test,y_pred)
print("Accuracy",accuracy)
print(classification_report(y_test,y_pred))'''

'from sklearn.naive_bayes import MultinomialNB\nfrom sklearn.metrics import accuracy_score , classification_report\nmodel = MultinomialNB()\n#model.fit(x_train,y_train)\ny_pred = model.predict(x_test)\naccuracy = accuracy_score(y_test,y_pred)\nprint("Accuracy",accuracy)\nprint(classification_report(y_test,y_pred))'

In [38]:
message = ["congrats!! you won a jackpot of 70000"]
user_vector = vectorizer.transform(message)
#prediction = model.predict(user_vector)
if prediction [0] ==1:
  print("this is spam")
else:
  print("not spam")

this is spam

In [39]:
from sklearn.svm import LinearSVC
model = LinearSVC()
model.fit(x_vectorised ,y_train)

LinearSVC()

In [44]:
from sklearn.metrics import accuracy_score
y_pred = model.predict(x_test_vectorised )
accuracy = accuracy_score(y_test,y_pred)
print("Accuracy",accuracy)

Accuracy 0.9829596412556054

In [41]:
message = [" congratulations you have won "]
user_vector = vectorizer.transform(message)
prediction = model.predict(user_vector)
if prediction [0] ==1:
  print("this is spam")
else:
  print("not spam")

this is spam

In [42]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[963   2]
 [ 17 133]]

#CONFUSION - MATRIX !!!!!!!!

In [46]:
#[[963   2]  #[[TN FP]
 #[ 17 133]] #  [FN TP]]

In [48]:
'''from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)'''

'from sklearn.ensemble import RandomForestClassifier\n\nmodel = RandomForestClassifier(\n    n_estimators=100,\n    random_state=42\n)'

In [49]:
df.head(10)

   label                                               text
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...
5      1  FreeMsg Hey there darling it's been 3 week's n...
6      0  Even my brother is not like to speak with me. ...
7      0  As per your request 'Melle Melle (Oru Minnamin...
8      1  WINNER!! As a valued network customer you have...
9      1  Had your mobile 11 months or more? U R entitle...

In [50]:
df.tail(10)

      label                                               text
5562      0  Ok lor... Sony ericsson salesman... I ask shuh...
5563      0                                Ard 6 like dat lor.
5564      0  Why don't you wait 'til at least wednesday to ...
5565      0                                       Huh y lei...
5566      1  REMINDER FROM O2: To get 2.50 pounds free call...
5567      1  This is the 2nd time we have tried 2 contact u...
5568      0              Will Ì_ b going to esplanade fr home?
5569      0  Pity, * was in mood for that. So...any other s...
5570      0  The guy did some bitching but I acted like i'd...
5571      0                         Rofl. Its true to its name